### ISSUE TITLE
404 error in content-viewer - Lost connection to server

### ISSUE THREAD

**Issue by Garlov** [enonic/app-contentviewer#9]
If admin is hosted on anything but `/admin`, content-viewer gets a 404 from a rest call to : `/admin/rest/content/page/template/isRenderable`

To test, just set the vhost config to:
```
mapping.test.host = localhost
mapping.test.source = /xp/admin
mapping.test.target = /admin
mapping.test.idProvider.system = default
```
Then go to Content Studio and open the content-viewer app for any content. This will create a 404 error and invalidate the session. Content-viewer needs to take the `/xp/` into account when running the rest call.

**Comment by alansemenov** [comment]
Released as 1.5.3
